# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy
    # - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    main: .
    binary: envdiff
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    goarm:
      - "7"
    ignore:
      # build fails with this combination
      - goos: windows
        goarch: arm64
    ldflags:
      - -s
      - -w
      - -X main.version=v{{.Version}}
      - -X main.gitCommit={{.ShortCommit}}
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format: binary
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
